
services:
  # 1. Base SQL & Géospatiale
  postgres:
    image: postgis/postgis:16-3.4
    container_name: aerowise_postgis
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: aerowise_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Base Vectorielle (Embeddings)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: aerowise_qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

  # 3. Base de Graphe (Connaissances)
  neo4j:
    image: neo4j:5.15-community
    container_name: aerowise_neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      # On force l'utilisateur à être neo4j pour éviter les problèmes de droits
      NEO4J_AUTH: neo4j/password_graph
    # C'EST LA LIGNE MAGIQUE : Elle permet de nettoyer les processus morts (pid 7)
    init: true 
    volumes:
      - neo4j_data:/data

volumes:
  postgres_data:
  qdrant_data:
  neo4j_data: